#!/usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR/node
docker build -t fwartner/node:latest .
docker push fwartner/node:latest
cd $DIR/../

cd $DIR/php-composer
docker build -t fwartner/php-composer:latest .
docker push fwartner/php-composer:latest
cd $DIR/../

set -e

HASH=$(git rev-parse HEAD)

cd $DIR/../

git archive --format=tar --worktree-attributes $HASH | tar -xf -  -C $DIR/app/packaged

cd $DIR/app/packaged
docker run --rm -v $(pwd):/opt -w /opt fwartner/php-composer:latest composer install
docker run --rm -v $(pwd):/opt -w /opt fwartner/node:latest npm install
docker run --rm -v $(pwd):/opt -w /opt fwartner/node:latest npm rebuild node-sass --force
docker run --rm -v $(pwd):/opt -w /opt fwartner/node:latest npm run production

cp .env.example .env

cd $DIR/app
docker build -t fwartner/laravelapp:latest .
docker push fwartner/laravelapp:latest